In [1]:
import numpy as np

In [3]:
ar1=np.array([[1,2],[5,6]])

In [4]:
ar2=np.array([[3,4],[7,8]])

In [5]:
ar1+ar2

array([[ 4,  6],
       [12, 14]])

In [6]:
np.sqrt(ar1)

array([[1.        , 1.41421356],
       [2.23606798, 2.44948974]])

In [7]:
ar1.sum()

14

In [9]:
ar1.max()

6

In [10]:
np.where(ar1>4)

(array([1, 1], dtype=int64), array([0, 1], dtype=int64))