In [1]:
import numpy as np

In [2]:
zeros=np.zeros((2,5))

In [3]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
ones=np.ones((2,2))

In [11]:
ones

array([[1., 1.],
       [1., 1.]])

In [19]:
lsp=np.linspace(1,5,12)

In [20]:
lsp

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
emp=np.empty((2,2))

In [22]:
emp

array([[1., 1.],
       [1., 1.]])